# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RequestCheckerUI(object):
    def setupUi(self, RequestCheckerUI):
        RequestCheckerUI.setObjectName("RequestCheckerUI")
        RequestCheckerUI.resize(1027, 827)
        icon = QtGui.QIcon.fromTheme("nani?!")
        RequestCheckerUI.setWindowIcon(icon)
        RequestCheckerUI.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(RequestCheckerUI)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 680, 411, 71))
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 660, 341, 16))
        self.label.setObjectName("label")
        self.CheckPB = QtWidgets.QProgressBar(self.centralwidget)
        self.CheckPB.setGeometry(QtCore.QRect(10, 760, 1021, 21))
        self.CheckPB.setProperty("value", 24)
        self.CheckPB.setObjectName("CheckPB")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(560, 700, 64, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 710, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 710, 47, 13))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 700, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 120, 311, 481))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 100, 141, 20))
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(390, 120, 256, 481))
        self.textBrowser.setObjectName("textBrowser")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(343, 70, 41, 551))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(7)
        self.line.setMidLineWidth(7)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 100, 171, 16))
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(730, 120, 256, 481))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 100, 161, 16))
        self.label_6.setObjectName("label_6")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(7, 610, 991, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(7)
        self.line_2.setMidLineWidth(7)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 60, 991, 20))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(7)
        self.line_3.setMidLineWidth(7)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 630, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(580, 730, 361, 31))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(530, 670, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 650, 201, 16))
        self.label_7.setObjectName("label_7")
        self.textEdit_Visual = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Visual.setEnabled(False)
        self.textEdit_Visual.setGeometry(QtCore.QRect(1010, 0, 20, 20))
        self.textEdit_Visual.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_Visual.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textEdit_Visual.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_Visual.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_Visual.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_Visual.setUndoRedoEnabled(False)
        self.textEdit_Visual.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_Visual.setObjectName("textEdit_Visual")
        self.textEdit_Visual_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Visual_2.setEnabled(False)
        self.textEdit_Visual_2.setGeometry(QtCore.QRect(990, 0, 20, 20))
        self.textEdit_Visual_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_Visual_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textEdit_Visual_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_Visual_2.setLineWidth(0)
        self.textEdit_Visual_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_Visual_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_Visual_2.setUndoRedoEnabled(False)
        self.textEdit_Visual_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_Visual_2.setObjectName("textEdit_Visual_2")
        self.textEdit_Visual_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Visual_3.setEnabled(False)
        self.textEdit_Visual_3.setGeometry(QtCore.QRect(1000, 0, 20, 20))
        self.textEdit_Visual_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit_Visual_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.textEdit_Visual_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_Visual_3.setLineWidth(0)
        self.textEdit_Visual_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_Visual_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_Visual_3.setUndoRedoEnabled(False)
        self.textEdit_Visual_3.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit_Visual_3.setObjectName("textEdit_Visual_3")
        RequestCheckerUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RequestCheckerUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1027, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        RequestCheckerUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RequestCheckerUI)
        self.statusbar.setObjectName("statusbar")
        RequestCheckerUI.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(RequestCheckerUI)
        self.action.setCheckable(False)
        self.action.setObjectName("action")
        self.menu_2.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(RequestCheckerUI)
        QtCore.QMetaObject.connectSlotsByName(RequestCheckerUI)

    def retranslateUi(self, RequestCheckerUI):
        _translate = QtCore.QCoreApplication.translate
        RequestCheckerUI.setWindowTitle(_translate("RequestCheckerUI", "RequestCheckerUI 0.0001b"))
        self.label.setText(_translate("RequestCheckerUI", "Вставьте URL для проверки по одному на каждую строку."))
        self.lcdNumber.setToolTip(_translate("RequestCheckerUI", "<html><head/><body><p>Цикл начинается с нуля.</p></body></html>"))
        self.label_2.setText(_translate("RequestCheckerUI", "Цикл повторяется уже"))
        self.label_3.setText(_translate("RequestCheckerUI", "-й раз"))
        self.pushButton.setText(_translate("RequestCheckerUI", "Старт/Стоп"))
        self.label_4.setText(_translate("RequestCheckerUI", "Текущий статус проверки"))
        self.label_5.setText(_translate("RequestCheckerUI", "Хорошие HTTP-ответы сервера"))
        self.label_6.setText(_translate("RequestCheckerUI", "Плохие HTTP-ответы сервера"))
        self.pushButton_2.setText(_translate("RequestCheckerUI", "Очистить поля"))
        self.checkBox.setToolTip(_translate("RequestCheckerUI", "Это нужно для простой постановки на fulltime-проверку. Проверка будет повторяться бесконечно, что позволит Вам своевременно узнавать о любых проблемах."))
        self.checkBox.setText(_translate("RequestCheckerUI", "Зациклить бесконечно (до нажатия \"Стоп\")"))
        self.label_7.setText(_translate("RequestCheckerUI", "Количество повторений цикла"))
        self.menu.setTitle(_translate("RequestCheckerUI", "Проверка урлов"))
        self.menu_2.setTitle(_translate("RequestCheckerUI", "Помощь"))
        self.action.setText(_translate("RequestCheckerUI", "О программе"))
        self.action.setWhatsThis(_translate("RequestCheckerUI", "<html><head/><body><p>Написано в 2018 по приколу ради всеобщего блага. Язык - python 3.7, с использованием PyQt5, Reuest. Исходники на https://github.com/AgeofCreations/RequestChecker</p></body></html>"))

